-- Enable UUID extension
create extension if not exists "uuid-ossp";

-- USERS / STUDENTS (synced with Telegram data)
create table if not exists public.students (
  id bigint generated by default as identity primary key,
  tg_id bigint unique not null, -- Telegram User ID
  full_name text,
  tg_username text,
  phone_number text,
  photo_url text,
  lang text default 'uz',
  role text default 'student', -- 'admin', 'teacher', 'student'
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- EXAMS
create table if not exists public.exams (
  id bigint generated by default as identity primary key,
  title text not null,
  description text,
  duration_min integer not null default 30, -- Duration in minutes
  start_time timestamp with time zone, -- Scheduled start time
  end_time timestamp with time zone, -- Scheduled end time (deadline)
  access_code text, -- Optional password for private exams
  attempts_limit integer default 1,
  pass_min_correct integer default 0, -- Minimum correct answers to pass
  shuffle_questions boolean default false,
  shuffle_answers boolean default false,
  review_policy text default 'immediate', -- 'immediate', 'after_close', 'manual'
  is_published boolean default false,
  owner_tg_id bigint references public.students(tg_id),
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- QUESTIONS
create table if not exists public.questions (
  id bigint generated by default as identity primary key,
  exam_id bigint references public.exams(id) on delete cascade not null,
  type text default 'multiple_choice', -- 'multiple_choice', 'text', 'boolean'
  text text not null,
  image_url text,
  audio_url text,
  points integer default 1,
  explanation text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- QUESTION OPTIONS (for multiple choice)
create table if not exists public.question_options (
  id bigint generated by default as identity primary key,
  question_id bigint references public.questions(id) on delete cascade not null,
  text text not null,
  is_correct boolean default false,
  ord integer default 0 -- Order for display
);

-- ATTEMPTS (Student taking an exam)
create table if not exists public.attempts (
  id bigint generated by default as identity primary key,
  exam_id bigint references public.exams(id) on delete cascade not null,
  student_tg_id bigint references public.students(tg_id) not null,
  state text default 'active', -- 'active', 'submitted', 'graded'
  started_at timestamp with time zone default timezone('utc'::text, now()) not null,
  submitted_at timestamp with time zone,
  score integer, -- Calculated score (percentage or points)
  duration_spent_sec integer,
  meta jsonb, -- Store metadata like user_agent, warnings_count
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- ATTEMPT ANSWERS (Student's answers)
create table if not exists public.attempt_answers (
  id bigint generated by default as identity primary key,
  attempt_id bigint references public.attempts(id) on delete cascade not null,
  question_id bigint references public.questions(id) on delete cascade not null,
  option_ids jsonb, -- Array of selected option IDs (for multiple choice)
  text_answer text, -- For text questions
  is_correct boolean, -- Calculated by server
  points_awarded integer,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(attempt_id, question_id)
);

-- NOTIFICATIONS (For scheduled exams)
create table if not exists public.notifications (
  id bigint generated by default as identity primary key,
  student_tg_id bigint references public.students(tg_id) not null,
  exam_id bigint references public.exams(id) on delete cascade not null,
  scheduled_for timestamp with time zone not null,
  is_sent boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- RLS POLICIES (Basic security)
alter table public.students enable row level security;
alter table public.exams enable row level security;
alter table public.questions enable row level security;
alter table public.attempts enable row level security;

-- Allow public read for now (simplification for prototype, refine later)
create policy "Public read exams" on public.exams for select using (true);
create policy "Public read questions" on public.questions for select using (true);
